"""updated price column type for Order model

Revision ID: 0a61a5c02276
Revises: f50eb586e395
Create Date: 2020-07-08 19:25:20.042797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a61a5c02276'
down_revision = 'f50eb586e395'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('price', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('total_price', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'total_price')
    op.drop_column('orders', 'price')
    # ### end Alembic commands ###
