"""updated country column for Client model

Revision ID: 17dbfba4b631
Revises: 3779904f2585
Create Date: 2020-07-08 19:32:39.815919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17dbfba4b631'
down_revision = '3779904f2585'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('country', sa.String(), nullable=False))
    op.add_column('clients', sa.Column('country', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'country')
    op.drop_column('admins', 'country')
    # ### end Alembic commands ###
