"""removed country column from Client model

Revision ID: 3779904f2585
Revises: 0a61a5c02276
Create Date: 2020-07-08 19:31:57.361464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3779904f2585'
down_revision = '0a61a5c02276'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'county')
    op.drop_column('clients', 'county')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('county', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('admins', sa.Column('county', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
