"""updated title for Tea model

Revision ID: 758ccbfe740e
Revises: 28c07f53f108
Create Date: 2020-07-08 04:41:10.338143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '758ccbfe740e'
down_revision = '28c07f53f108'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tea', sa.Column('title', sa.String(), nullable=False))
    op.drop_constraint('tea_long_title_key', 'tea', type_='unique')
    op.drop_constraint('tea_short_title_key', 'tea', type_='unique')
    op.create_unique_constraint(None, 'tea', ['title'])
    op.drop_column('tea', 'short_title')
    op.drop_column('tea', 'long_title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tea', sa.Column('long_title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tea', sa.Column('short_title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tea', type_='unique')
    op.create_unique_constraint('tea_short_title_key', 'tea', ['short_title'])
    op.create_unique_constraint('tea_long_title_key', 'tea', ['long_title'])
    op.drop_column('tea', 'title')
    # ### end Alembic commands ###
