"""updated price column type for Tea model

Revision ID: 970b869b675c
Revises: a9d811b872b8
Create Date: 2020-07-08 04:55:52.159242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '970b869b675c'
down_revision = 'a9d811b872b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tea', sa.Column('price', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tea', 'price')
    # ### end Alembic commands ###
