"""updated unique constraints

Revision ID: ec20e299d82e
Revises: 17dbfba4b631
Create Date: 2020-07-10 00:27:01.673626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec20e299d82e'
down_revision = '17dbfba4b631'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('admin_email_key', 'admins', ['email'])
    op.drop_constraint('admins_email_key', 'admins', type_='unique')
    op.create_unique_constraint('client_email_key', 'clients', ['email'])
    op.drop_constraint('clients_email_key', 'clients', type_='unique')
    op.create_unique_constraint('company_email_key', 'company_contacts', ['email'])
    op.drop_constraint('company_contacts_email_key', 'company_contacts', type_='unique')
    op.create_unique_constraint('tea_title_unique_key', 'tea', ['title'])
    op.drop_constraint('tea_title_key', 'tea', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('tea_title_key', 'tea', ['title'])
    op.drop_constraint('tea_title_unique_key', 'tea', type_='unique')
    op.create_unique_constraint('company_contacts_email_key', 'company_contacts', ['email'])
    op.drop_constraint('company_email_key', 'company_contacts', type_='unique')
    op.create_unique_constraint('clients_email_key', 'clients', ['email'])
    op.drop_constraint('client_email_key', 'clients', type_='unique')
    op.create_unique_constraint('admins_email_key', 'admins', ['email'])
    op.drop_constraint('admin_email_key', 'admins', type_='unique')
    # ### end Alembic commands ###
